version: "3.7"


services:
  site:
    build: .
    restart: always
    environment:
      - APP_URL=http://localhost
      - APP_DEBUG=True
      - PRODUCT=False
      - DB_HOST=pg_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=testDB
      - MEMCACHED_HOST=memcached_db
      - MEMCACHED_PORT=11211
    volumes:
      - ./public:/var/www/public
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - ./storage:/var/www/storage
      - ./resources:/var/www/resources
      - ./data/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - pg_db
    container_name: site

  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testDB
    volumes:
      - ./db_pg:/var/lib/postgresql/data/
    container_name: pg_db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    container_name: adminer

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./data/nginx/nginx.debug.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - site

  memcached_db:
    image: memcached:latest
    restart: always
    command:
      - '--memory-limit=100'
